cislo1 = float(input("zadej desetinne cislo"))
cislo2 = float(input("zadej desetinne cislo"))
soucet = float(cislo1) + float(cislo2)
print(f"{soucet:.2f}")
podil = int(cislo1) / int(cislo2)
print(f"{podil:.2f}")
soucin = int(cislo1) + int(cislo2)
print(f"{soucin:.2f}")
rozdil = int(cislo1) - int(cislo2)
print(f"{rozdil:.2f}")
